#!/usr/bin/bash

# Deprecations are silenced because node does not silence
# library deprecation warnings if they aren't contained in
# node_modules. Since we are bundling, this would be noisy.

EXTENSION_PATH=$(dirname $0)
exec node --no-deprecation "$EXTENSION_PATH/dist/index.js" $@
